[package]
name = "sound"
version = "0.1.0"
authors = ["Ben Spalding"]
edition = "2018"
repository="https://github.com/bnspalding/rust-sound"
readme="README.md"
license= "MIT"

[dependencies]
maplit = "1.0.2"
lazy_static = "1.4.0"
unicode-segmentation = "1.7.1"
